name: Node.js Test and Deploy Staging

on:
  push:
    branches:
    - master

jobs:
  test-and-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'skittlz444/hc_site'
        ref: 'master'
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm run-script test a
      env:
        CI: true
    - name: Build App
      run: npm run-script build
      env:
        CI: true
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.HC_WEBSITE_STAGING_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets. HC_WEBSITE_DEPLOY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets. HC_WEBSITE_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'build'
    - name: Remove build
      uses: JesseTG/rm@v1.0.0
      with:
        path: build
      
